services:
  redis:
    image: "redis:alpine"
    restart: unless-stopped
    container_name: llm-craft.redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: "password"
      REDIS_PORT: 6379
      REDIS_DATABASES: 1
    volumes:
      - ./.data/redis:/data